# Generated by Django 5.2 on 2025-04-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_remove_venta_cantidad_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipo_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ventas.tipoventa'),
        ),
    ]
