# Generated by Django 5.2 on 2025-04-13 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventario",
            old_name="cantidad_mininma",
            new_name="cantidad_minima",
        ),
    ]
