# Generated by Django 5.2 on 2025-04-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0002_rename_cantidad_mininma_inventario_cantidad_minima"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="cantidad",
            field=models.IntegerField(default=0),
        ),
    ]
