# Generated by Django 5.2 on 2025-04-21 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0003_producto_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
