# Generated by Django 5.2 on 2025-04-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0003_alter_producto_imagen"),
        ("Productos", "0004_alter_producto_imagen"),
    ]

    operations = []
